name: CI - Build & Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ "9.0" ]     # your SDK version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore NuGet packages
        run: |
          dotnet restore

      - name: Build solution
        run: |
          dotnet build --no-restore --configuration Release

      - name: Run unit tests only
        run: |
          export ASPNETCORE_ENVIRONMENT=Test

          # Run only the unit test projects, skip IntegrationTests
          dotnet test src/Acme.ProductService/Acme.ProductService.Tests/Acme.ProductService.Tests.csproj \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx"

          dotnet test src/Acme.RecommendationService/Acme.RecommendationService.Tests/Acme.RecommendationService.Tests.csproj \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx"

          dotnet test src/Acme.UserProfileService/Acme.UserProfileService.Tests/Acme.UserProfileService.Tests.csproj \
            --no-build \
            --configuration Release \
            --logger "trx;LogFileName=test-results.trx"



      - name: Publish each API project (artifacts)
        run: |
          # Product Service
          dotnet publish src/Acme.ProductService/Acme.ProductService.Api/Acme.ProductService.Api.csproj -c Release -o ./artifacts/ProductService

          # User Service
          dotnet publish src/Acme.UserProfileService/Acme.UserProfileService.Api/Acme.UserProfileService.Api.csproj -c Release -o ./artifacts/UserProfileService

          # Recommendation Service
          dotnet publish src/Acme.RecommendationService/Acme.RecommendationService.Api/Acme.RecommendationService.Api.csproj -c Release -o ./artifacts/RecommendationService

          # API Gateway
          dotnet publish src/Acme.ApiGateway/Acme.ApiGateway/Acme.ApiGateway.csproj -c Release -o ./artifacts/ApiGateway

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: acme-build-artifacts
          path: artifacts

# ---------------------------------------
# CD : DEPLOY PRODUCT SERVICE TO AZURE
# ---------------------------------------
  deploy-product-dev:
      - name: Deploy Product Service to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: acme-product-dev
          publish-profile: ${{ secrets.AZURE_PRODUCTSERVICE_PUBLISH_PROFILE }}
          package: ProductService


